site_name: Prova RTD ciro
site_url: https://readthedocs.org/projects/rtd-comemipiace/
site_description: Un altro bel tool per scrivere documentazione in Markdown da visualizzare su RTD

repo_url: https://github.com/cirospat/rtd-comemipiace
repo_name: rtd-comemipiace
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo3.png
  palette:
    scheme: preference
  language: it

nav:
  - Home: README.md
  - Prova pagina: provapagina.md
  - Altra pagina: pippo.md
  - Un altra pagina ancora: pippo2.md
  - Più pagine ancora: pippo3.md
  - Directory:
    - api/client.md
    - api/client2.md
    - api/expansions.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols


## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cirospat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/cirospat
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/rtd-comemipiace
    - icon: fontawesome/solid/envelope
      link: mailto:cirospat@gmail.com
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/rtd-comemipiace/

## setting dal progetto originale = https://github.com/up42/up42-py/blob/master/mkdocs.yml
