## Project information
site_name: Bozza di template per la redazione del piano triennale informatica da parte delle PA
site_url: https://bozza-template-redazione-pianotriennale-ict-per-pa.readthedocs.io/it/latest/
site_description: bozza-template-redazione-pianotriennale-ict-per-pa
site_author: Ciro Spataro Comune di Palermo

## Repository
repo_url: https://github.com/cirospat/bozza-template-redazione-pianotriennale-ict-per-pa
repo_name: bozza-template-redazione-pianotriennale-ict-per-pa
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/palermologo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - Strategia: strategia.md
  - Cap. 1 - Servizi: capitolo-1-servizi.md
  - Cap. 2 - Dati: capitolo-2-dati.md
  - Cap. 3 - Piattaforme: capitolo-3-piattaforme.md
  - Cap. 4 - Interoperabilità: capitolo-4-interoperabilita.md
  - Cap. 5 - Sicurezza informatica: capitolo-5-sicurezza-informatica.md
  - Cap. 6 - Struemnti e modelli per l'innovazione: capitolo-6-strumenti-modelli-innovazione.md
  - Cap. 7 - Governare la trasformazione digitale: capitolo-7-governare-trasformazione-digitale.md
  

plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
  

## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ComunePalermo
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/bozza-template-redazione-pianotriennale-ict-per-pa
    - icon: fontawesome/solid/envelope
      link: mailto:protocollo@cert.comune.palermo.it
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/bozza-template-redazione-pianotriennale-ict-per-pa/
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://twitter.com/ComunePalermo" title="Comune di Palermo " target="_blank">Comune di Palermo </a> | 2021 | CC BY 4.0 Int Licence
