## Project information
site_name: Prova RTD ciro
site_url: https://rtd-comemipiace.readthedocs.io/it/latest/
site_description: Un altro bel tool per scrivere documentazione in Markdown da visualizzare su RTD
site_author: Ciro Spataro

## Repository
repo_url: https://github.com/cirospat/rtd-comemipiace
repo_name: rtd-comemipiace
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo3.png
  palette:
    - scheme: default
      primary: gray
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  

nav:
  - Prova pagina 0: provapagina0.md
  - Prova pagina 1: provapagina1.md
  - Prova pagina 2: provapagina2.md
  - Tabelle: tabella.md
  - Directory macro agomento:
    - micro argomento 1: nomedirectory/nomefile.md
    - micro argomento 2: nomedirectory/nomefile2.md
    - micro argomento 3: nomedirectory/nomefile3.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
  

## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cirospat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/cirospat
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/rtd-comemipiace
    - icon: fontawesome/solid/envelope
      link: mailto:cirospat@gmail.com
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/rtd-comemipiace/
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: Ciro Spataro | 2021 | CC BY 4.0 Int Licence
