site_name: Prova RTD ciro
site_url: https://readthedocs.org/projects/rtd-comemipiace/
site_description: Un altro bel tool per scrivere documentazione in Markdown da visualizzare su RTD

repo_url: https://github.com/cirospat/rtd-comemipiace
repo_name: rtd-comemipiace
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo3.png
  palette:
    scheme: preference
  language: it

nav:
  - Home: README.md
  - Prova pagina: provapagina.md
  - Altra pagina: pippo.md
  - Un altra pagina ancora: pippo2.md
  - Più pagine ancora: pippo3.md
  - Directory:
    - api/client.md
    - api/client2.md
    - api/expansions.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
